# Generated by Django 3.2.25 on 2024-04-07 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaveSystem', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='applicationModel',
        ),
    ]
