# Generated by Django 3.2.25 on 2024-04-09 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaveSystem', '0002_delete_applicationmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account_data',
        ),
    ]
