# Generated by Django 3.2.25 on 2024-04-07 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('phoneno', models.IntegerField(blank=True, null=True)),
                ('hostelNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('roomNumber', models.IntegerField(blank=True, null=True)),
                ('fromDate', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('toDate', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.SmallIntegerField(choices=[(-1, 'Pending'), (0, 'Rejected'), (1, 'Approved')], default=-1)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_applications', to='accounts.role')),
            ],
        ),
    ]
