# Generated by Django 3.2.25 on 2024-04-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffapplication',
            name='hostelNumber',
        ),
        migrations.RemoveField(
            model_name='staffapplication',
            name='roomNumber',
        ),
        migrations.RemoveField(
            model_name='staffapplication',
            name='time',
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
