# Generated by Django 3.2.25 on 2024-04-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_studentapplication_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='parentEmail',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
